# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crowdd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crowdd

  target 'CrowddTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrowddUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'

end
